export const actionTypes = {
  FETCH_MAG_INFOS: 'FETCH_MAG_INFOS',
  FETCH_MAG_NUMBER_DETAILS: 'FETCH_MAG_NUMBER_DETAILS'
}

export const mutationTypes = {
  SET_MAG_NEWS: 'SET_MAG_NEWS',
  SET_MAG_NUMBERS: 'SET_MAG_NUMBERS',
  SET_SELECTED_MAG_NUMBER: 'SET_SELECTED_MAG_NUMBER',
  SET_MAG_NUMBER_DETAILS: 'SET_MAG_NUMBER_DETAILS'
}
