export const getterTypes = {
  GET_DRAWER_VALUE: 'GET_DRAWER_VALUE',
  GET_DIALOG_VALUE: 'GET_DIALOG_VALUE',
  GET_SNACKBAR_VALUE: 'GET_SNACKBAR_VALUE'
}
export const actionTypes = {
  TOGGLE_DRAWER_ACTION: 'TOGGLE_DRAWER_ACTION',
  OPEN_DIALOG_ACTION: 'OPEN_DIALOG_ACTION',
  CLOSE_DIALOG_ACTION: 'CLOSE_DIALOG_ACTION',
  SHOW_SNACKBAR_ACTION: 'SHOW_SNACKBAR_ACTION',
  CLOSE_SNACKBAR_ACTION: 'CLOSE_SNACKBAR_ACTION'
}
export const mutationTypes = {
  TOGGLE_DRAWER: 'TOGGLE_DRAWER',
  OPEN_DIALOG: 'OPEN_DIALOG',
  CLOSE_DIALOG: 'CLOSE_DIALOG',
  SHOW_SNACKBAR: 'SHOW_SNACKBAR',
  CLOSE_SNACKBAR: 'CLOSE_SNACKBAR',
  SET_SNACKBAR_TEXT: 'SET_SNACKBAR_TEXT',
  CLEAR_SNACKBAR_TEXT: 'CLEAR_SNACKBAR_TEXT'
}
