export const actionTypes = {
  REQUEST_LOGIN: 'REQUEST_LOGIN',
  REQUEST_REGISTER: 'REQUEST_REGISTER',
  REQUEST_SUBSCRIPTION: 'REQUEST_SUBSCRIPTION'
}

export const mutationTypes = {
  SET_USER: 'SET_USER'
}