export const actionTypes = {
  FETCH_CHRONICLES_INFOS: 'FETCH_CHRONICLES_INFOS', 
  FETCH_CHRONICLE_DETAILS: 'FETCH_CHRONICLE_DETAILS' 
}
export const mutationTypes = {
  SET_CHRONICLES_NEWS : 'SET_CHRONICLES_NEWS', 
  SET_CHRONICLES : 'SET_CHRONICLES',
  SET_CHRONICLE_DETAILS : 'SET_CHRONICLE_DETAILS', 
  SET_SELECTED_CHRONICLE : 'SET_SELECTED_CHRONICLE'
}
