export const actionTypes = { 
  FETCH_GLOSSARY_INFOS: 'FETCH_GLOSSARY_INFOS', 
  FETCH_DEFINITION_DETAILS: 'FETCH_DEFINITION_DETAILS' 
}
export const mutationTypes = { 
  SET_GLOSSARY_NEWS: 'SET_GLOSSARY_NEWS', 
  SET_DEFINITIONS: 'SET_DEFINITIONS',
  SET_DEFINITION_DETAILS: 'SET_DEFINITION_DETAILS', 
  SET_SELECTED_DEFINITION: 'SET_SELECTED_DEFINITION'
} 