export const actionTypes = {
  FETCH_BLOG_INFOS: 'FETCH_BLOG_INFOS',
  FETCH_ARTICLE_DETAILS: 'FETCH_ARTICLE_DETAILS'
}
export const mutationTypes = {
  SET_BLOG_NEWS: 'SET_BLOG_NEWS',
  SET_TRENDING_ARTICLES: 'SET_TRENDING_ARTICLES',
  SET_LATEST_ARTICLES: 'SET_LATEST_ARTICLES',
  SET_ARTICLE_DETAILS: 'SET_ARTICLE_DETAILS'
}
