export const actionTypes = {
  FETCH_STORIES_INFOS: 'FETCH_STORIES_INFOS',
  FETCH_STORY_DETAILS: 'FETCH_STORY_DETAILS',
  FETCH_COLLECTION_DETAILS: 'FETCH_COLLECTION_DETAILS'
}

export const mutationTypes = {
  SET_STORIES_NEWS: 'SET_STORIES_NEWS',
  SET_STORIES: 'SET_STORIES',
  SET_SELECTED_STORY: 'SET_SELECTED_STORY',
  SET_STORY_DETAILS: 'SET_STORY_DETAILS',
  SET_COLLECTIONS: 'SET_COLLECTIONS',
  SET_SELECTED_COLLECTION: 'SET_SELECTED_COLLECTION',
  SET_COLLECTION_DETAILS: 'SET_COLLECTION_DETAILS'
}
