
export const getterTypesRoot = {
  GET_HOME_NEWS: 'GET_HOME_NEWs'
}
export const actionTypes = {
  FETCH_HOME_INFOS: 'FETCH_HOME_INFOS',
  SET_SELECTED_CATEGORY_ACTION: 'SET_SELECTED_CATEGORY_ACTION'
}
export const mutationTypes = {
  SET_HOME_NEWS: 'SET_HOME_NEWS',
  SET_LATEST_POSTS: 'SET_LATEST_POSTS',
  SET_CATEGORIES: 'SET_CATEGORIES',
  SET_SELECTED_CATEGORY: 'SET_SELECTED_CATEGORY'
}
