export const actionTypes = {
  FETCH_HOME_INFOS: 'FETCH_HOME_INFOS'
}
export const mutationTypes = {
  SET_HOME_NEWS: 'SET_HOME_NEWS',
  SET_LATEST_POSTS: 'SET_LATEST_POSTS',
  SET_CATEGORIES: 'SET_CATEGORIES',
  SET_SELECTED_CATEGORY: 'SET_SELECTED_CATEGORY'
}
